# Generated by Django 5.2.1 on 2025-06-03 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('lider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipes_lideradas', to=settings.AUTH_USER_MODEL)),
                ('membros', models.ManyToManyField(related_name='equipe_participantes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('data_limite', models.DateField()),
                ('concluida', models.BooleanField(default=False)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipe')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
